
[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/x-cray/logrus-prefixed-formatter"
  version = "0.5.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/flachnetz/go-admin"
  version = "1.5.2"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  source = "https://github.com/flachnetz/go-metrics.git"

[[constraint]]
  name = "github.com/eSailors/go-datadog"
  version = "1.0.1"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.17.0"

[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/clock"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  version = "0.3.4"

[[constraint]]
  name = "github.com/apache/thrift"
  revision = "88591e32e710a0524327153c8b629d5b461e35e0"


[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.17.1"

[[constraint]]
  name = "github.com/modern-go/gls"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gchaincl/sqlhooks"
  revision = "0ce9882095c14a1155631cf466fd5d8369177683"
